const COURSES_ACTION_TYPES = {
    ADD_COURSE: "ADD_COURSE", 
    GET_COURSES: "GET_COURSES",
    DELETE_COURSE: "DELETE_COURSE",
    UPDATE_COURSE: "UPDATE_COURSE"
};

export default COURSES_ACTION_TYPES;
